### ISSUE TITLE
Error when showing Charts

### ISSUE THREAD

**Issue by AndreasBomholtz** [kromitgmbh/titra#108] opened 2022-03-16 10:42 UTC
When I look on the Charts page, I can see this error in the console:

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at i.value (/node_modules/frappe-charts/dist/frappe-charts.min.umd.js:1:35122)
    at i.value (/node_modules/frappe-charts/dist/frappe-charts.min.umd.js:1:34642)
    at ResizeObserver.boundDrawFn (/node_modules/frappe-charts/dist/frappe-charts.min.umd.js:1:33495)
```

**Comment by faburem** [comment] 2022-03-17 13:22
Thanks for reporting this issue. Unfortunately this is caused by the library we use to render the charts so we will have to create an issue for the library at https://github.com/frappe/charts. I don't think there is anything we can do on the titra side to prevent this but I am always open for suggestions!

**Comment by noraj** [comment] 2022-07-04 10:05
The error is also viewable on the docker logs not only on the user browser console:

![image](https://user-images.githubusercontent.com/16578570/177132398-dfb1da96-56af-4346-8fca-58d7ed52d5dd.png)

Also by default the _Time distribution by task_ chart is not rendered

![image](https://user-images.githubusercontent.com/16578570/177132607-5291c223-393d-4c99-b94d-7fed8d81dff1.png)

But as soon as you open the JS dev console, the chart appears

![image](https://user-images.githubusercontent.com/16578570/177132723-a589059f-b177-4f2e-a88d-dbeb60c45687.png)

**Comment by faburem** [comment] 2022-09-28 11:28
Closing this issue since there is nothing we can do about it until the root cause is fixed in frappe-charts upstream.

**Closed by faburem** 2022-09-28 11:28 UTC
Labels: wontfix
