### ISSUE TITLE
Edits of Tracking Records Are Not Saved

### ISSUE THREAD

**Issue by CaptainPackers** [kromitgmbh/titra#136] opened 2022-06-15 21:55 UTC
When I try to edit a record for a project/task for a given day to update the hours, for example, the record is completely deleted after I make the updates and click the Save button.

**Comment by faburem** [comment] 2022-06-16 08:07
Can you please provide a bit more context (e.g screenshots of the steps taken). Is this also happening on https://app.titra.io ? I just tried on two environments and cannot reproduce the issue.

**Comment by CaptainPackers** [comment] 2022-06-16 13:07
This does also happen on app.titra.io, from which the screen shots below were taken. The first shows an initial entry, the second the desired edit in the edit record api, and the third is after clicking on the save button. As you can see the original record is gone after trying to edit it. This happens in both brave-browser and in firefox
![Screenshot_1](https://user-images.githubusercontent.com/7439853/174076198-fe639f62-0aca-4613-93cd-00e8dd7a8c02.png)
![Screenshot_2](https://user-images.githubusercontent.com/7439853/174076203-903b35d0-0a64-4250-bb5e-b66847d9adc4.png)
![Screenshot_3](https://user-images.githubusercontent.com/7439853/174076206-7e0b50aa-1c8e-4699-960a-a4fda250c2a3.png)
.

**Comment by faburem** [comment] 2022-06-16 17:16
Thanks for the screenshots! This helps a lot with troubleshooting. I don't think the time entry is "gone", but as you can see in the second screenshot the date is changed to June 15th. Which time zone are you located in? I will review the code and make sure we are converting all times properly to UTC but first I need to be able to reproduce it on my side.

Thanks for your help,
Fabian

**Comment by CaptainPackers** [comment] 2022-06-16 20:01
My timezone is EDT (UTC-4).

Thanks

**Comment by faburem** [comment] 2022-06-19 08:24
fixed in titra 0.79.0!

**Closed by faburem** 2022-06-19 08:24 UTC

**Comment by CaptainPackers** [comment] 2022-06-19 12:57
Thanks. Will try new version tomorrow.

**Comment by CaptainPackers** [comment] 2022-06-20 14:48
Can't pull new image:
`
$ docker-compose pull
Pulling mongodb ... error
Pulling titra   ... error

ERROR: for titra  Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution

ERROR: for mongodb  Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution
ERROR: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution
Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution

`

**Comment by CaptainPackers** [comment] 2022-06-20 15:10
New image tested OK. Thanks.
