### ISSUE TITLE
Dates are one day off on save

### ISSUE THREAD

**Issue by emiliobool** [kromitgmbh/titra#8] opened 2020-01-19 06:34 UTC
So whenever I save a tracking item it saves the date from one day before. Let's say I have selected: Sat, 18.01.2020 and I click save, it changes to 17.01.2020 and it keeps going back as much as I press the save button, so if I make 2 changes to an item it ends up being 2 days off.

**Comment by faburem** [comment] 2020-01-20 13:25
Hi,
unfortunately I cannot reproduce the problem on my side. Can you please provide the following information to help us track down the problem:
- Where did you encounter this behaviour (app.titra.io, self-hosted, locally)
- Is this only happening when updating an existing time entry or also when you create a new one?
- What timezone are you in?

Thanks for your help!

**Comment by emiliobool** [comment] 2020-01-20 18:07
I'm running the docker image via docker-compose, not sure what timezone the image is and not sure if the client browser timezone matters but I'm GMT-7. The date shown was correct before saving, but wrong after saving. 

It didn't happen last night, but it is happening again today, and I just checked and it happens on both new entry and edit. I also tried editing one of the correct entries from last night and it subtracted 1 day on save. Not sure if it is related to the time of the day because it also failed during the night the other day too, so not sure. 

I'm also attaching a screenshot with the docker logs 

![image](https://user-images.githubusercontent.com/2165828/72748546-c674a600-3b74-11ea-8eb1-d8395088937d.png)

**Comment by faburem** [comment] 2020-01-21 12:53
Thanks for the additional information. It was a bug handling client side UTC timestamps which is fixed in release [0.9.1](https://github.com/kromitgmbh/titra/releases/tag/0.9.1). The updated release is currently being built on [Docker hub](https://hub.docker.com/repository/docker/kromit/titra):
Once the build is finished, please update your local instance using `docker pull kromit/titra`. If the release fixes your issue feel free to close it. Thanks for reporting - your support is very much appreciated 🧐👍

**Comment by emiliobool** [comment] 2020-01-31 07:06
Hi, I just came back from vacations, I updated the image and tried adding some hours, it seems the subtracting issue is gone, but I noticed something interesting that I don't know if it is somehow related. When I'm saving the hours the date is 30.01.2020 but on the details page it shows 29.01.2020, I'm not sure if any other records are being affected. It is also midnight here, not sure if that matters.

**Comment by faburem** [comment] 2020-01-31 10:35
Hi @emiliobool,
I can confirm this problem. Unfortunately we introduced some timezone bugs during the recent migration to modern npm libraries (e.g. the details view). We have browsed the entire code base for similar issues and hopefully fixed all of them now in release [0.9.3](https://github.com/kromitgmbh/titra/releases/tag/0.9.3). Again, the updated release is currently being built on [Docker hub](https://hub.docker.com/r/kromit/titra). Once the build is finished, please update your local instance using `docker pull kromit/titra`.

Thanks for your on-going support!

**Comment by faburem** [comment] 2020-03-09 14:16
Were you able to verify if the issue has been fixed? Since there was no update on this issue in some time I would otherwise close it.
Thanks for your feedback!

**Comment by faburem** [comment] 2020-03-28 18:03
Closing issue due to inactivity, feel free to re-open it if the problem still occurs in the latest version of titra.

**Comment by colintufts** [comment] 2021-04-22 01:23
Hey @faburem I'm Seeing this issue in the latest build from docker-compose as well. Let me know what you need from me and I can provide logs, etc

**Comment by faburem** [comment] 2021-04-22 05:02
Hi,
couple of questions:
- are you running titra locally?
- which timezone are you located in?
- if you are running titra on a dedicated server, is it located in a different time zone?

That would help us figure out the root cause.

Thanks for your feedback,
Fabian

**Comment by faburem** [comment] 2021-05-04 18:48
@colintufts any update on this issue? Otherwise I would close it again...

**Comment by colintufts** [comment] 2021-05-07 10:05
Sorry for the late reply, it didn't come in via github notifications.

1.  Yes running locally, kromit/titra from docker hub
2.  Timezone: America/New_York
3.  Dedicated server is also running in America/New_york

Saving results in time input exactly 24 hours previous to input time.

**Comment by faburem** [comment] 2021-05-09 15:58
Hi,
I tried to reproduce this issue by setting my time zone to America/New York but unfortunately without success. Can you please provide a little bit more information so I can better understand what's happening? Maybe some screenshots would help to see what's going on.

Thanks,
Fabian

**Comment by faburem** [comment] 2021-05-16 15:55
Please provide more information on this issue, otherwise I have to close it due to inactivity. Thanks!

**Closed** 2021-06-08 13:12 UTC
Labels: bug
