### ISSUE TITLE
No segregation

### ISSUE THREAD

**Issue by noraj** [kromitgmbh/titra#140] opened 2022-07-04 10:49 UTC
There isn't really any segregation, if you know the URL of a private project you can view the data logged in it by direct URL access, eg. `http://localhost:3000/list/timecards/hLv9hv5DfXxBSNuCF`.

The project is private (not public) and the user was not added in the list, but yet the user can see the `Detailed`, `Worktime` and `Charts` tabs, only `Daily` and `Total` are shown as empty because the user has no permission. Also the project name is not shown.

It means the timecards endpoint is leaking data to unauthorized users.

**Comment by faburem** [comment] 2022-07-15 11:25
Thanks for reporting this, the issue is fixed in titra version 0.79.3.
If you still experience this or similar issues feel free to re-open this or create a new issue!

**Closed as completed by faburem** 2022-07-15 11:25 UTC
Labels: bug
