### ISSUE TITLE
Can't see swimlanes on first wekan import

### ISSUE THREAD

**Issue by nikolay-martynov** [kromitgmbh/titra#46] opened 2021-01-25 05:47 UTC
When editing a project imported from wekan and you click "Check" button, columns to import are displayed but swimlanes are not displayed. If I click the button for the second time then swimlanes are displayed. It was working without quirks in 0.32.0 but not anymore in 0.40.2.

![image](https://user-images.githubusercontent.com/13433348/105665686-9f1f8a00-5ee8-11eb-9b25-dca6fd12d36e.png)

![image](https://user-images.githubusercontent.com/13433348/105665820-e148cb80-5ee8-11eb-9e9c-c5e1f31e5b90.png)

![image](https://user-images.githubusercontent.com/13433348/105665991-48668000-5ee9-11eb-8c83-cf768330d6e1.png)

![image](https://user-images.githubusercontent.com/13433348/105666162-b612ac00-5ee9-11eb-9a13-e6cfd452aac4.png)

![image](https://user-images.githubusercontent.com/13433348/105666208-cf1b5d00-5ee9-11eb-986f-04a27d13a8d0.png)

**Comment by faburem** [comment] 2021-01-27 10:45
Hi,
thanks for reporting this issue. Unfortunately I could not reproduce it all the time, but I tried to improve the behaviour in titra 0.41.0 which is currently being built on Docker hub.

Please let us know if you are still having issues.

**Comment by faburem** [comment] 2021-02-04 09:10
Can you please confirm if the issue has been resolved? If I don't hear back I will close this issue.

Thanks for your feedback!

**Closed** 2021-02-11 15:46 UTC
Labels: bug
